### ISSUE TITLE
Some shortcuts don't work

### ISSUE THREAD

**Issue by bummfelix** [notaapp/issues#1]
⌥⌘E and ⌘Z are not working on my laptop, nothing happens when I press them.
I'm on a MacbookPro 2013 with macOS Catalina (10.15.3) with german keyboard layout (although changing to englisch didn't make it work). 
It's the only application where ⌘Z is not working.
I can confirm that ⌥R & ⌘P are working as intended.

Caret Version: 0.8.0

**Comment by bummfelix** [comment]
Update: on 0.9.0 ⌥⌘E works!

**Comment by astoilkov** [comment]
Is that your keyboard layout: https://i.stack.imgur.com/ErgQC.jpg? If yes, can you try pressing ⌘Y and see if it works like undo?

**Comment by bummfelix** [comment]
yes and yes!

**Comment by astoilkov** [comment]
Does the issue gets fixed if you switch your input language from German to English?

![image](https://user-images.githubusercontent.com/884810/86124002-19b73100-bae3-11ea-9c57-87ba5fb23d30.png)

**Comment by bummfelix** [comment]
No, I tried that already. After switching to English it still only works with ⌘Y

**Comment by aheidelberg** [comment]
If the keyboard layout is German and the input language is English it is supposed to work with `⌘Y` isn't it (if we are talking about the letter Y on the physical keyboard)?
That's how it is for me in Nota and in every other app.

If I set my input language to German it works with `⌘Z` (letter Z on the physical keyboard).

This is what my keyboard input language usually looks like. Maybe this helps.
<img width="120" alt="Screenshot 2020-07-07 at 01 31 07" src="https://user-images.githubusercontent.com/22153826/86667686-290e1100-bff2-11ea-8286-77cf98658104.png">

**Comment by bummfelix** [comment]
It is fixed with 0.10.1 for me now. (⌘Z works as intended with german input language)

**Comment by astoilkov** [comment]
Yes. This is fixed in the Nota update from yesterday. Closing this issue.
