### ISSUE TITLE
Incorrect preview for code block

### ISSUE THREAD

**Issue by borekb** [notaapp/issues#10]
This Markdown:

~~~md
```md
_Search terms: X, Y, Z_
```
~~~

is previewed as:

<img width="311" alt="Screenshot 2020-08-18 at 09 35 29" src="https://user-images.githubusercontent.com/101152/90484214-2bf23a80-e136-11ea-94cc-b3e4404b3109.png">

Correct preview would be:

<img width="300" alt="Screenshot 2020-08-18 at 09 36 16" src="https://user-images.githubusercontent.com/101152/90484309-488e7280-e136-11ea-86ed-64d17d1476be.png">

**Comment by borekb** [comment]
Somehow, the "md" specifier is the problem, both of these are previewed correctly:

~~~md
```txt
_Search terms: X, Y, Z_
```
~~~

~~~md
```
_Search terms: X, Y, Z_
```
~~~

**Comment by astoilkov** [comment]
I replicated the bug and fixed it. The fix will be included in the next release.

Thanks!
