### ISSUE TITLE
Expand selection in links – small issue

### ISSUE THREAD

**Issue by borekb** [notaapp/issues#15]
✅ Correct sequence of `cmd-e` when I start from the URL part:

<img width="638" alt="Screenshot 2020-09-16 at 09 20 35" src="https://user-images.githubusercontent.com/101152/93304904-0cfecb00-f7fe-11ea-9cd7-527995d3870e.png">

<img width="638" alt="Screenshot 2020-09-16 at 09 21 13" src="https://user-images.githubusercontent.com/101152/93304918-0f612500-f7fe-11ea-9aea-73121d5a9395.png">

<img width="638" alt="Screenshot 2020-09-16 at 09 20 59" src="https://user-images.githubusercontent.com/101152/93304922-0ff9bb80-f7fe-11ea-958a-f17c53f89de9.png">

<img width="638" alt="Screenshot 2020-09-16 at 09 21 29" src="https://user-images.githubusercontent.com/101152/93304910-0ec88e80-f7fe-11ea-9810-bd91b84e5d10.png">

<img width="638" alt="Screenshot 2020-09-16 at 09 21 39" src="https://user-images.githubusercontent.com/101152/93304908-0e2ff800-f7fe-11ea-864d-668c6d308f74.png">

---

❌ Incorrect sequence of `cmd-e` when I start from the text part:

<img width="638" alt="Screenshot 2020-09-16 at 09 23 26" src="https://user-images.githubusercontent.com/101152/93305121-5fd88280-f7fe-11ea-8fb4-4254a77b8f0f.png">

<img width="638" alt="Screenshot 2020-09-16 at 09 23 37" src="https://user-images.githubusercontent.com/101152/93305128-623adc80-f7fe-11ea-919e-c0fbfab526b4.png">

<img width="638" alt="Screenshot 2020-09-16 at 09 23 48" src="https://user-images.githubusercontent.com/101152/93305125-61a24600-f7fe-11ea-98d6-99c4db7af32e.png">

[The fourth step is missing]

<img width="638" alt="Screenshot 2020-09-16 at 09 23 56" src="https://user-images.githubusercontent.com/101152/93305123-6109af80-f7fe-11ea-9d65-d5185a303ff2.png">

**Comment by astoilkov** [comment]
We have fixed this. The fix will be available in the next release. Thanks for reporting!
