### ISSUE TITLE
Incorrect syntax highlighting for URLs

### ISSUE THREAD

**Issue by Overload119** [notaapp/issues#28]
Here is the URL in question.

`https://www.internalfb.com/intern/wiki/Marketplace_Growth/Listing_Improvements_Framework_(LIF)/`

![image](https://user-images.githubusercontent.com/1012072/98428650-4d890100-2057-11eb-9db6-437c4f6d40ce.png)

**Comment by Overload119** [comment]
Notice that the last `)/` are not included in the highlighting and as a result the link is broken when you try to click into it as well.

**Comment by erusev** [comment]
Fixed, we'll include the fix in the next release.
