### ISSUE TITLE
Nested lists don't render correctly in the preview experiment

### ISSUE THREAD

**Issue by borekb** [notaapp/issues#3]
The Preview experiment (cmd-shift-r) doesn't render nested lists correctly in 0.9.0:

```md
1. First item
    2. Nested
    3. items
```

Rendered as:

![Screenshot 2020-06-30 at 13 12 14-shadow](https://user-images.githubusercontent.com/101152/86119767-5e3ad080-bad3-11ea-8c85-9acd72125b69.png)

**Comment by bummfelix** [comment]
I feel like this is the case for normale line breaks as well:
`test
test`
renders as
![image](https://user-images.githubusercontent.com/4069819/86120700-14eb8080-bad5-11ea-9d3b-f426c0fa4236.png)

**Comment by borekb** [comment]
@bummfelix That is correct though: https://babelmark.github.io/?text=test%0Atest

**Comment by bummfelix** [comment]
I see, feels still a little bit weird.
When commenting on github, line breaks are rendered "normally" though.

**Comment by borekb** [comment]
Yeah, GitHub comments and pull requests are not entirely GFM, which is confusing. But close enough 😄.

**Comment by erusev** [comment]
@borekb This seems consistent w/ CommonMark — https://spec.commonmark.org/dingus/. The issue seems to be with the `2.` in `2. Nested`. Changing that to `1.` renders a nested list.

**Comment by borekb** [comment]
🤦‍♂️ @erusev you're completely right, I didn't pay attention to what numbers Nota generated for me.

So this issue would be better written a feature request for Nota to maintain "logical" numbering when I indent/outdent list items. For example, if I have this list:

```md
1. One
2. Two
3. Three
```

and indent the second line via `Tab`, it would be good to get this:

```md
1. One
    1. Two
2. Three
```

**Comment by borekb** [comment]
My report is incorrect, I've created #4 as a feature request for automatic numbering. Thanks a lot for clearing that up.
