### ISSUE TITLE
Feature Request: Jekyll support

### ISSUE THREAD

**Issue by diethardsteiner** [notaapp/issues#34]
As a blog writer I'd like to use Nota with Jekyll (static website generator). I guess the only difference here is that pictures reside in the `<git-repo>/images` folder whereas the actual markdown files within `<git-repo>/_posts`.

**Comment by astoilkov** [comment]
Hi,

I like the idea of having better support for Jekyll. You can choose where Nota saves images via the `assetPath` config in your `.nota.ini` file so images go inside `<git-repo>/images`. What else could we do?

**Comment by diethardsteiner** [comment]
Thanks for your reply. Where do I find this `.nota.ini` file? Or should I create it somewhere, like the user's home folder?

**Comment by astoilkov** [comment]
It either exists in your workspace folder(the folder you have opened in Nota) or you can create it. There you can specify `assetPath=/images`.

**Comment by erusev** [comment]
@diethardsteiner If you don't have a `.nota.ini` in your workspace, you can simply paste an image in the editor, and this will create one for you and offer to open it so that you can set the path where you want images to go.

**Comment by diethardsteiner** [comment]
Ok this is very interesting - the workspace support. I checked and I can find the file in `~/Documents/Nota/.nota.ini`. So how do I go about creating a new workspace (So I'd like to register my Jekyll git repo as a workspace with Nota)? I see there are some menu items in regards to Workspace, but not one in regards to creating/registering a new one.

**Comment by astoilkov** [comment]
You can do `File -> Open` and select your Jekyll git repo. Nota will open it and then you can create your `.nota.ini` file either by pasting an image like @erusev suggested or doing it manually.

**Comment by diethardsteiner** [comment]
Thanks. So I tried this. When Nota opens the file (there is an arrow next to the filename in the tab), the old workspace is still there, and it then correctly complains that the file is outside the current workspace. How do I move properly to the new workspace?

**Comment by astoilkov** [comment]
Did you try to select the Jekyll folder with `File -> Open` and not the file?

**Comment by diethardsteiner** [comment]
Ok, thanks, that worked! 
Alright, I shall buy a license now too.

**Comment by astoilkov** [comment]
Yes, thanks. We will do something to make this feature more obvious. Thanks!

P.S. Closing this issue now. If you have any more questions don't hesitate to write to us.
