### ISSUE TITLE
Bug: Clicking on Heading within Go-to-Heading HuD doesn't jump to selected heading within Markdown doc

### ISSUE THREAD

**Issue by diethardsteiner** [notaapp/issues#35]
When using the Go-to-Heading HuD and clicking on one heading, the expected behaviour is that Nota jumps to this heading within the markdown document, however, in the latest version of Nota this is not happening occasionally.
I am not quite sure what is causing the issue. The only thing I did before this happened is change the file name.
Update: I tried to rename the file and then use the Go-to-Heading HuD, but it's working correctly now.
P.S.: I've got a long document and I tested header anchors at the beginning and end of the doc, so "the jump" would have been visible.
I guess for now there is not enough to go by, so feel free to close this ticket and I can recreate one if I hit the issue again.

**Comment by astoilkov** [comment]
@diethardsteiner I wasn't able to replicate the problem but I made a change that should shield against a similar problem. The change will be included in the next release which is coming soon.

I will close this issue but if the issue arises again please comment here so we can continue with the investigation. Thanks for the report!
