### ISSUE TITLE
Unable to save file

### ISSUE THREAD

**Issue by mrbbp** [notaapp/issues#39]
creat new file
write
command +s, a window open but unable to select a place, it crash with a nice window who asking to restart because an error occured...

**Comment by astoilkov** [comment]
Hi @mrbbp 👋,

We fixed the bug. The next release will include the fix. Meanwhile, we know that if your File Sidebar is visible this shouldn't happen – you can try that.

Thanks for the report!

**Comment by mrbbp** [comment]
ok with Sidebar open, no more crash. thanks 👍
