### ISSUE TITLE
Automatically maintain numbers in ordered lists

### ISSUE THREAD

**Issue by borekb** [notaapp/issues#4]
_Mentioned in https://github.com/notaapp/issues/issues/3#issuecomment-652451215 but is probably its own feature request._

If I have a numbered list, it would be nice if Nota automatically maintained the numbers for me. For example, I have this list:

```md
1. Apples
2. Oranges
3. Bananas
```

and move the last line one up (`alt-↑`), I get this:

```md
1. Apples
3. Bananas
2. Oranges
```

Would be nice if I got this:

```md
1. Apples
2. Bananas
3. Oranges
```

---

Another case is nested lists:

```md
1. One
2. Two
3. Three
```

If I indent the second line via `Tab`, it would be great to get this:

```md
1. One
    1. Two
2. Three
```

**Comment by astoilkov** [comment]
The next update will include improved support for ordered lists which will include the cases in this issue.
