### ISSUE TITLE
Nota Doesn't Load Consistently On MacBook Pro Running 10.13.6

### ISSUE THREAD

**Issue by rb81** [notaapp/issues#43]
I find myself having to force-quit a failed load (blank screen and hanging) then re-opening the app, each time I want to use it.

**Comment by astoilkov** [comment]
This is bad 😞 . Will you help us figure this out? Can you send us your `~/Library/Logs/Nota/Nota.log` file so we can see if any errors happen.

**Comment by astoilkov** [comment]
We have a theory of why this is happening. We even have an experimental fix that will land in the release next week but any additional information will be helpful.

**Comment by rb81** [comment]
@astoilkov - Do you have an email address I can email the log?

**Comment by astoilkov** [comment]
Yes. Send it over to support@nota.md. Thanks.

**Comment by rb81** [comment]
Sent.

**Comment by rb81** [comment]
FYI- Seems like it might be a memory issue. With enough patience, the app does load. I don't have enough files/folders to be causing this though. And, I definitely have enough RAM.

**Comment by astoilkov** [comment]
Thanks for the logs. We are now sure you are hitting the case that we already fixed. The fix will be available in the next release.

**Comment by rb81** [comment]
Great news! Looking forward to it.

**Comment by rb81** [comment]
FYI- Just received this error for the first time:

![Screen Shot 2021-02-15 at 2 59 25 PM](https://user-images.githubusercontent.com/48117105/107938301-975e7d00-6f9e-11eb-946b-0e418ea0bf2c.png)

**Comment by astoilkov** [comment]
With the new Nota release, this error should no longer exist. You can check and let us know.

Thanks for helping us with all your feedback.

**Comment by astoilkov** [comment]
@rb81 Did the error go away?

I saw that you wrote a few issues here – I hope you are liking Nota so far. I hope you don't mind asking for your impressions on Nota? Even a short sentence would be helpful. Thanks!
