### ISSUE TITLE
⌘ + N Issue with different languages.

### ISSUE THREAD

**Issue by iL-0** [notaapp/issues#434]
Hello,
`⌘ + N` Should search notes right?

It works fine with notes with English title (or filename), but.. it doesn't work with notes with Korean title (or filename), it doesn't show notes.
As well as `⌘ + N` command, I think the text search is fine, but it still cannot find notes with Korean title.

Could you fix this?
Thanks.

**Comment by astoilkov** [comment]
I fixed this. The next release that will come in the next few weeks will include the fix.
