### ISSUE TITLE
Spellcheck Corrections Not Working

### ISSUE THREAD

**Issue by rb81** [notaapp/issues#44]
Spellcheck seems to highlight incorrectly spelled words quite quickly, but there doesn't seem to be a way to correct the highlighted word. The expected right-click brings up the cut/copy/paste context menu, but there's no option to change the spelling. (Log shows some error related to spellcheck.)

**Comment by astoilkov** [comment]
Yes, we discovered that auto-correction and word suggestions don't work under High Sierra and below.

**Comment by astoilkov** [comment]
We fixed this. The next release will include the fix. Thanks for reporting it.

**Comment by rb81** [comment]
Awesome! My pleasure!

**Comment by astoilkov** [comment]
We published a new Nota release. It includes the spellchecker fix. Thanks for reporting!
