### ISSUE TITLE
Pasting From Word Generates Image

### ISSUE THREAD

**Issue by rb81** [notaapp/issues#45]
First time trying to paste from Word prompts me to edit the config file to set a folder for assets. After doing so, the pasted content from Word appears as an image. Personally, I don't see the use for this. Do people really want to copy content from Word and paste them as images in a markdown file? Alternatively, a general "Paste As Image" might be more relevant, but shouldn't be default behavior.

**Comment by astoilkov** [comment]
Hmm, that is definitely strange. Do you mean the macOS Word app or the online version?

**Comment by rb81** [comment]
Copying text from a Microsoft Word document using Microsoft Word for Mac 16.43 on High Sierra 10.13.6.

**Comment by astoilkov** [comment]
We have fixed the issue. The next release this week will include the fix. Thanks for the many things you have helped us with.

**Comment by rb81** [comment]
My pleasure!

**Comment by astoilkov** [comment]
Today we published a new Nota release. It includes the fix when pasting content from Word. Thanks for the report!
