### ISSUE TITLE
Slow performance with larger markdown files

### ISSUE THREAD

**Issue by diethardsteiner** [notaapp/issues#47]
When I open a longer markdown doc in the Nota app is becomes really slow. 
As a developer, when writing technical documentation, I want the Nota app to be responsive/snappy even when the content of my markdown document grows.

**Comment by astoilkov** [comment]
One of our priorities is performance so I am glad if you help us out discover what's wrong. Can you share a slow document or tell us how big of a document is causing problems and on what computer you are running Nota?

**Comment by astoilkov** [comment]
Additionally, is the opening of the document slow, the scrolling, the typing, or something else?

**Comment by diethardsteiner** [comment]
The opening is very quick. It's the scrolling and typing that are affected.

**Comment by astoilkov** [comment]
Can you share some information about the size of the document and your system?

**Comment by diethardsteiner** [comment]
MBP, macOS Big Sur, 16GB RAM, quad-core CPU
This particular markdown doc is 113KB in size. It has a lot of code blocks in them.

**Comment by astoilkov** [comment]
I tested a big document with lots of code blocks and indeed the scrolling and typing was slow. I made some performance improvements so now it's significantly better. The next release will include those changes.

Thanks for the report! If you have any other performance problems or any other feedback be welcome to contact us again.

**Comment by diethardsteiner** [comment]
Excellent, thanks a lot for the quick fix!

**Comment by astoilkov** [comment]
Today we published the new Nota release. It includes the improvements to the typing and scrolling performance.

Thanks for your feedback!
