### ISSUE TITLE
Spell checker gives incorrect suggestion

### ISSUE THREAD

**Issue by borekb** [notaapp/issues#5]
I first wrote this:

> Let's sumarise this.

And got a red squiggly, rightly so. There's a suggestion to fix it:

<img width="312" alt="Screenshot 2020-07-14 at 06 29 34" src="https://user-images.githubusercontent.com/101152/87384187-66970f00-c59b-11ea-92ad-7d690189e63b.png">

Which I did but then got another red squiggly and a new suggestion:

<img width="321" alt="Screenshot 2020-07-14 at 06 30 40" src="https://user-images.githubusercontent.com/101152/87384248-8d554580-c59b-11ea-9486-46968f970268.png">

It's probably because in the first case, Nota is suggesting a British spelling (summari**s**e) instead of American English (summari**z**e).

In the browser (here in this GitHub issue, for example) I get the correct en-US suggestion the first time around:

<img width="232" alt="Screenshot 2020-07-14 at 06 34 26" src="https://user-images.githubusercontent.com/101152/87384467-1d938a80-c59c-11ea-8db4-c514d1ca3fdf.png">

**Comment by astoilkov** [comment]
Does the same thing happen if you try this in a native macOS app like Notes? (For me it does)

**Comment by borekb** [comment]
Nope, 'Notes' also suggest the "correct" (en-US) spelling:

<img width="225" alt="Screenshot 2020-07-14 at 11 51 27" src="https://user-images.githubusercontent.com/101152/87411744-6bbe8300-c5c8-11ea-8c6f-f5ff4f3bcf4e.png">

**Comment by astoilkov** [comment]
Hmm, interesting. What is your setting for `System Preferences -> Keyboard -> Text -> Spelling`? This is what it looks for m:
![image](https://user-images.githubusercontent.com/884810/87414077-d75a1d80-c5d3-11ea-9f03-7bb343084d3f.png)
![image](https://user-images.githubusercontent.com/884810/87413724-5a2ea880-c5d3-11ea-810c-a1182c0ffcd7.png)
![image](https://user-images.githubusercontent.com/884810/87413674-46834200-c5d3-11ea-9d80-8d60f352d11f.png)

**Comment by borekb** [comment]
Also **Automatic by Language**:

<img width="780" alt="Screenshot 2020-07-14 at 12 32 56" src="https://user-images.githubusercontent.com/101152/87415925-2ef58a80-c5ce-11ea-9d97-5a1d7a0992d9.png">

**Comment by astoilkov** [comment]
We made some improvements to the suggestion engine to bring it closer to the native macOS version. I have tested this scenario and it seems to work fine now. Can you verify it as well?

**Comment by borekb** [comment]
I can confirm that "Let's sumarise this" gets corrected correctly the first time around! 🎉
