### ISSUE TITLE
Backlink disappears after moving file that links to it

### ISSUE THREAD

**Issue by shawnsui** [notaapp/issues#53]
ex: 
File 1 links to File 2.
File 1 gets moved to another folder.
File 2 no longer shows that there is a backlink to it but the link from file 1 still works.

**Comment by astoilkov** [comment]
Yes, you are right. This is a bug. We will immediately fix it and release an update soon. Thank you!

**Comment by astoilkov** [comment]
We fixed the bug in the last release. Thanks for reporting.

Closing this issue.
