### ISSUE TITLE
Feature request: automatic image management

### ISSUE THREAD

**Issue by darsnack** [notaapp/issues#55]
I just started moving some of my notes from Ulysses/iA Writer, I am really loving the app so far. It strikes the balance between a text editor and prose app that I need (as you can tell I currently use two apps).

But there is one feature of database apps like Ulysses that I absolutely love — the ability to take screenshots of PDFs/webpages then just drag the screenshot into my notes. I am wondering if something similar could be achieved in Nota while still adhering to the "plain files" mantra.

So, the request: can you add a feature where if I drag and drop an image into my note (not an image file but more like a pasteboard), Nota saves the image as a file in a configurable location in the workspace. Basically, for a plain files only setup, most users will have an "images" folder where they store all their images for notes. All I want is for Nota to automatically save drag+dropped images to such a folder for me, then add the path into my note.

Hopefully my description makes sense.

**Comment by darsnack** [comment]
Never mind, I just realized that already happens. I was dragging the wrong thing into Nota! Amazing, fantastic app.

**Comment by astoilkov** [comment]
I saw that you have proposed multiple feature requests — thank you, this helps a lot! If you have any other feedback — don't like something or just some impressions you can also write to us at [hello@nota.md](mailto:hello@nota.md).

Thank you for the kind words.

**Comment by erusev** [comment]
@darsnack You can also paste image files (and image data) to achieve the same result -- I thought I should mention this in case it's helpful 😊
