### ISSUE TITLE
Backlinks dialog is empty.

### ISSUE THREAD

**Issue by niteshkumarniranjan** [notaapp/issues#58]
![image](https://user-images.githubusercontent.com/20199181/119842326-355dce00-bf24-11eb-9e47-4dc574831c6b.png)

I am not sure if I am doing something wrong, but it seems like the backlinks aren't working.

**Comment by astoilkov** [comment]
Hmm. It's hard to tell from the screenshot if there should be a backlink for this file. Is the `OTP.md` file linked somewhere? If not, you should link to `OTP.md` to see backlinks.

I see that there is a link to `Concurrency.md`. If you open `Concurrency.md` and open the backlinks popup there you should see `OTP.md` there.

**Comment by niteshkumarniranjan** [comment]
Oh! My bad I haven't linked `OTP.md` in `Concurrency.md`.
Since I can't navigate by clicking the backlinks or anything I thought the backlink modal will be an easy way to jump to backlinks of current files.

PS: I just figured it out doing `⌘ + Click` does let me navigate. 🙈
Sorry!
