### ISSUE TITLE
'Tab' messes up indentation of fenced code blocks

### ISSUE THREAD

**Issue by borekb** [notaapp/issues#6]
I have this:

<img width="953" alt="Screenshot 2020-07-14 at 16 00 44" src="https://user-images.githubusercontent.com/101152/87434802-34ad9900-c5eb-11ea-8233-2d33568a79c7.png">

then press Tab and get this:

<img width="953" alt="Screenshot 2020-07-14 at 16 00 06" src="https://user-images.githubusercontent.com/101152/87434841-43944b80-c5eb-11ea-856f-c6ac9cb00a54.png">

Plain text before:

~~~
```js
export const resolvers = {
  Query: {
    search() {
      // ...
    }
  }
}
```
~~~

Plain text after:

~~~
    ```js
    export const resolvers = {
    Query: {
        search() {
        // ...
        }
    }
    }
    ```
~~~

**Comment by astoilkov** [comment]
Yes, I am stumbling on the same issue from time to time. We should definitely do something about it.

**Comment by borekb** [comment]
My workaround is to use multiple cursors (`cmd-alt-↓`) and press `space` 4 times.

**Comment by astoilkov** [comment]
I actually researched the topic a little bit. It seems the way it works in Nota only works that way in VSCode. This is why I decided to change the behavior and align it with other editors. The next release will include the fix.
