### ISSUE TITLE
Bug - Numbered List Indent/Outdent

### ISSUE THREAD

**Issue by joshua-russell** [notaapp/issues#63]
If I create a numbered lis and add a second list-item, tab to indent it, then shift-tab to outdent it, the numbered item "1." changes to "2." and the 2nd numbered item changes to "3." 
This does not recur if you do the same to subsequent non-indented numbered list items. 

Interestingly, if you attempt this on indented numbered list items, the first item stays "1." - however after indenting/outdenting the second indented list item, the second list item changes from "2." to "1." and additional indented list items are all numbered "1." instead of incrementing. This seems to hold true for all additional levels of indentation. 

![NotaNumberedList](https://user-images.githubusercontent.com/2198793/121970379-6de31180-cd44-11eb-9c8b-4fbe82c33b33.gif)

**Comment by astoilkov** [comment]
We fixed the bug. The next release will include the fix.

@joshua-russell Thank you for reporting. This is very valuable for us!

**Comment by astoilkov** [comment]
The fix landed in the last Nota release. The next release will include a lot more improvements to lists so stay tuned.

Closing this issue.
