### ISSUE TITLE
Editor's cursor position at end of document

### ISSUE THREAD

**Issue by led** [notaapp/issues#76]
### DESCRIPTION:
When clicking beyond the bottom of the edit window, the cursor is moved to the _nearest vertical position to the mouse click_ on the bottom line.

![nota-cursor-example](https://user-images.githubusercontent.com/395440/123070304-8bcb0900-d40b-11eb-9b20-efa659d37cda.gif)

### EXPECTED:
On clicking below the last line in the document, the typical behaviour is to move the editor's cursor to _the end of the edit text_.

### SOLUTION:
Make the behaviour consistent with other MacOS editors.

**Comment by astoilkov** [comment]
Great! It's important for us to be consistent with other apps. The next release will include this improvement.

**Comment by erusev** [comment]
@led These issues are beautiful! Thanks for taking the time to make them 🙏

**Comment by led** [comment]
To add to this, the issue extends to selections as well.

![nota-selection](https://user-images.githubusercontent.com/395440/123082806-588e7700-d417-11eb-91ed-9e3bcb9af999.gif)

When the pointer is dragged below the last edit line, the selection should extend to the last character rather than try to match the horizontal position of the pointer.

**Comment by led** [comment]
Resolved in Nota 0.30.0
