### ISSUE TITLE
Feature Request: Cmd+Enter opens link at caret.

### ISSUE THREAD

**Issue by Overload119** [notaapp/issues#8]
If I'm in a document and have something like this:

https://google.com and my caret is focus on this link, then hitting Cmd Enter should open it in the browser, similar to Cmd+Click does.

(ie. https://google.c|om) in here my caret is in the .com

**Comment by astoilkov** [comment]
We have Ctrl+Enter for following links with the keyboard. The shortcut is Ctrl+Enter because:
- Cmd+Enter is a taken shortcut. We keep it consistent with other code editors.
- Ctrl+Enter in Chrome does the same thing.

**Comment by astoilkov** [comment]
@Overload119 I am closing the issue. If you think Cmd Enter is a better shortcut let us know. Thanks!

**Comment by Overload119** [comment]
I think there is a false dichotomy between which hockey is better. Once the keyboard shortcuts page comes out we'll get to have our cake and eat it too.
