### ISSUE TITLE
Nota slow launch time

### ISSUE THREAD

**Issue by led** [notaapp/issues#85]
### DESCRIPTION:
Nota is slow to become responsive when launched.

When first launched, the menubar is filled out, but the actual menu items all mostly display as `(empty)`.

The actual menus shown are…

File, Edit, Line, Selection, Format, View, Go, Window, **Options**, Help

Nota only becomes responsive when the Options menu is removed, and this can take up to 30 seconds. The following GIF illustrates the startup time, the empty menus and the Options menu being displayed then removed.

![Nota startup menu issue](https://user-images.githubusercontent.com/395440/124192395-21763080-dabd-11eb-90c9-d5cc3216cd85.gif)

### EXPECTED:
Slightly faster startup time and the menu items stable and available from the get-go.

### THINGS TRIED:
- `open Help → Open Credits  //  quit  // re-launch`, but it's not made any improvement.
- removing the current `Nota` workspace directory

**Comment by led** [comment]
Resolved in Nota 0.30.0

Thank you for your hard work.

**Comment by astoilkov** [comment]
Great to hear! Quick question. What percent increase do you feel in Nota launch time? We calculated about 20% but it might be more in your case. I am curious.
