### ISSUE TITLE
windows/linux support schedule?

### ISSUE THREAD

**Issue by faldor20** [notaapp/issues#9]
I am just curious when this is planned. i didn't see it written anywhere, sorry i it is public already.
I am super keen to try this but just don't have, or particularly want a mac.

**Comment by erusev** [comment]
Hi @faldor20 and thanks for getting in touch! Windows and Linux support is something we will actually be looking at, but there's no timeline to share at this point.

**Comment by faldor20** [comment]
Are you guys using electron this time like in caret? Or are we going to have to wait for a much more complex port?

**Comment by erusev** [comment]
Yes, it's Electron, same as Caret :)

**Comment by Torsten-K** [comment]
A Linux app would be fantastic!

**Comment by CerebralMischief** [comment]
I certainly need a Linux App as there is where I spend most of my time these days.

**Comment by astoilkov** [comment]
We moved the voting for big features in our roadmap. You can vote and comment for Linux app [here](https://github.com/notaapp/roadmap/issues/10).

I am closing this issue in order to avoid confusion.
